import excel from "./input/excel";
import myFileSetting from "./input/myFileSetting";
import polyfill from "./polyfill/polyfill";
polyfill();
var config = [{ type: "file", disc: "excelファイルを選んでください" }];
var setting = new myFileSetting(false, "dialog_honshi.txt", config);
var tab = 1;
$.writeln(setting.my_save_folder_path[1]);
var excelfile = new File(setting.my_save_folder_path[1]);
$.writeln(excelfile.fsName);
var excel_instance = new excel(excelfile.fsName, ";", String(tab));
$.writeln(excel_instance.GetDataFromExcelPC());
// let excel_data = excel_instance.GetDataFromExcelPC();
